name: test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      dynamodb-local:
        image: "amazon/dynamodb-local@sha256:0efb33fe150fade10cac796c835c5fc68cd5b15596a12442e90dfe630c73ec9a"
        ports:
          - 8000:8000

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: install deps
        run: npm ci

      - name: lint
        run: npm run-script lint

      - name: test
        run: npm run-script test
        env:
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          files: .tap/report/lcov.info

